spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qihang-mall?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: Password123@mysql
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      # 密码
      #    password: 123321
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池的最大数据库连接数
          max-active: 8
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: cn.qihangerp.mts.domain;cn.qihangerp.domain;cn.qihangerp.module.domain;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志

sms:
  url: https://zincloudeshopapi.zinsoft.com/api.php/sms/sendSms
  appkey: fad00ef0ca6e8f018cce88fac8896805
  appsecret: PROJECT_NAMEed8bd917d4bf19d648e8ef1e78dcffd5
  template: SMS_474885198
  signName: 纳斯软件