server:
  port: 8088
spring:
  application:
    name: gateway
#  security:
#    user:
#      name: admin
#      password: password
    basic:
      enabled: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        username: nacos
#        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:8888 # sentinel控制台地址
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mall-route
          uri: lb://mall-api
          predicates:
            - Path=/api/mall-api/**
          filters:
            - StripPrefix=2

        - id: ams_api_route
          uri: lb://ams-api
          predicates:
            - Path=/api/ams-api/**
          filters:
            - StripPrefix=2

